kind: Deployment
apiVersion: apps/v1
metadata:
  name: producer
  namespace: rabbitmq
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: ismaelvp96/produce:v2
          env:
          - name: PYTHONUNBUFFERED
            value: "1"
          - name: QUEUE
            value: "test"
          - name: ROUTING_KEY
            value: "prueba_rmq"
 